{{-- report.blade.php --}}
@extends('layouts.app')
@section('title', 'DO Report')
@section('content')
<div class="ktm-page-header">
    <div>
        <h2 class="ktm-page-title"><i class="fa fa-chart-bar me-2" style="color:var(--primary)"></i>Delivery Order Report</h2>
        <div class="ktm-page-sub">Generated by {{ Auth::user()->Username }} — {{ now()->format('d M Y') }}</div>
    </div>
    <div style="display:flex;gap:10px">
        <button onclick="window.print()" class="btn-ktm-outline"><i class="fa fa-print me-1"></i>Print</button>
    </div>
</div>

<div class="row g-3 mb-4">
    @foreach([['Total','total','#6366f1'],['Draft','draft','#9ca3af'],['Submitted','submitted','#3b82f6'],['Under Review','underReview','#f59e0b'],['Approved','approved','#16a34a'],['Rejected','rejected','#dc2626']] as [$label,$key,$color])
    <div class="col-6 col-md-2">
        <div class="ktm-card text-center" style="padding:16px">
            <div style="font-size:26px;font-weight:800;color:{{ $color }}">{{ $summary[$key] }}</div>
            <div style="font-size:11px;color:var(--text-muted)">{{ $label }}</div>
        </div>
    </div>
    @endforeach
</div>

<div class="ktm-card">
    <div class="ktm-card-header d-flex justify-content-between">
        <span><i class="fa fa-table me-2"></i>Delivery Order Report Table</span>
        <span style="font-size:11px;color:var(--text-muted);font-weight:400">KTMeDOIS — Module 2</span>
    </div>
    <div class="p-0" style="overflow-x:auto">
        <table class="ktm-table">
            <thead>
                <tr>
                    <th>DO Number</th>
                    <th>Vendor</th>
                    <th>Customer</th>
                    <th>PO No</th>
                    <th>Project Ref</th>
                    <th>Submitted</th>
                    <th>Status</th>
                    <th>Remark</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $r)
                <tr>
                    <td style="font-weight:600">{{ $r->DONumber }}</td>
                    <td style="font-size:12px">{{ $r->vendor->CompanyName ?? '—' }}</td>
                    <td style="font-size:12px">{{ $r->Customer ?? '—' }}</td>
                    <td>{{ $r->PONumber ?? '—' }}</td>
                    <td style="font-size:12px">{{ $r->ProjectReference ?? '—' }}</td>
                    <td style="font-size:12px;color:var(--text-muted)">{{ $r->SubmittedDate ? \Carbon\Carbon::parse($r->SubmittedDate)->format('d M Y') : '—' }}</td>
                    <td>
                        @if($r->DOStatus==='Approved') <span class="badge-approved">Approved</span>
                        @elseif($r->DOStatus==='Rejected') <span class="badge-rejected">Rejected</span>
                        @elseif($r->DOStatus==='Submitted') <span class="badge-submitted">Submitted</span>
                        @elseif($r->DOStatus==='Under Review') <span class="badge-review">Under Review</span>
                        @else <span class="badge-inactive">Draft</span>
                        @endif
                    </td>
                    <td style="font-size:12px;color:var(--text-muted)">{{ Str::limit($r->Remark,60) }}</td>
                </tr>
                @empty
                <tr><td colspan="8" style="text-align:center;padding:32px;color:var(--text-muted)">No records found.</td></tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection
