@extends('layouts.app')
@section('title', 'System Audit Log')
@section('content')

{{-- Page header --}}
<div class="ktm-page-header no-print">
    <div style="display:flex;align-items:center;gap:14px">
        <img src="{{ asset('images/R.png') }}" alt="KTM" style="height:36px;width:auto">
        <div>
            <h2 class="ktm-page-title" style="color:#065f46">System Audit Log</h2>
            <div class="ktm-page-sub">All system actions recorded for audit and compliance purposes</div>
        </div>
    </div>
    <div style="display:flex;gap:10px">
        <button onclick="window.print()"
            style="display:inline-flex;align-items:center;gap:6px;padding:9px 18px;
                   background:linear-gradient(135deg,#064e3b,#065f46);color:#fff;
                   border:none;border-radius:9px;font-size:13px;font-weight:700;cursor:pointer">
            <i class="fa fa-print"></i> Print Report
        </button>
    </div>
</div>

{{-- Filter bar --}}
<div class="ktm-card mb-4 no-print">
    <div class="ktm-card-body">
        <form method="GET" action="{{ route('officer.audit') }}"
              style="display:flex;gap:12px;flex-wrap:wrap;align-items:flex-end">

            <div style="flex:1;min-width:160px">
                <label class="ktm-label">Search Username</label>
                <input type="text" name="username" value="{{ request('username') }}"
                    placeholder="e.g. vendor@ktm.com"
                    class="form-control ktm-input">
            </div>

            <div style="flex:1;min-width:140px">
                <label class="ktm-label">Action</label>
                <select name="action" class="form-select ktm-input">
                    <option value="">All Actions</option>
                    @foreach(['LOGIN','LOGOUT','LOGIN_FAILED','LOGIN_BLOCKED','VIEW_PROFILE',
                              'VENDOR_SYNC','DO_SUBMITTED','DO_APPROVED','DO_REJECTED',
                              'INVOICE_SUBMITTED'] as $act)
                    <option value="{{ $act }}" {{ request('action') === $act ? 'selected' : '' }}>
                        {{ $act }}
                    </option>
                    @endforeach
                </select>
            </div>

            <div style="flex:1;min-width:140px">
                <label class="ktm-label">From Date</label>
                <input type="date" name="date_from" value="{{ request('date_from') }}"
                    class="form-control ktm-input">
            </div>

            <div style="flex:1;min-width:140px">
                <label class="ktm-label">To Date</label>
                <input type="date" name="date_to" value="{{ request('date_to') }}"
                    class="form-control ktm-input">
            </div>

            <div style="display:flex;gap:8px">
                <button type="submit" class="btn-ktm"
                    style="background:linear-gradient(135deg,#064e3b,#065f46)">
                    <i class="fa fa-search"></i> Filter
                </button>
                <a href="{{ route('officer.audit') }}"
                   style="display:inline-flex;align-items:center;gap:6px;padding:9px 14px;
                          background:transparent;color:#065f46;border:1.5px solid #065f46;
                          border-radius:9px;font-size:13px;font-weight:700;text-decoration:none">
                    <i class="fa fa-times"></i> Clear
                </a>
            </div>

        </form>
    </div>
</div>

{{-- ── Audit Report Document ── --}}
<div class="audit-doc" id="audit-print">

    {{-- Report header (visible on print) --}}
    <div class="print-header" style="display:none">
        <div style="display:flex;justify-content:space-between;align-items:center;
                    margin-bottom:20px;padding-bottom:16px;border-bottom:2px solid #000">
            <div style="display:flex;align-items:center;gap:14px">
                <img src="{{ asset('images/R.png') }}" alt="KTM" style="height:50px">
                <div>
                    <div style="font-size:18px;font-weight:800">KTMeDOIS</div>
                    <div style="font-size:11px;color:#6b7280">Keretapi Tanah Melayu Berhad</div>
                </div>
            </div>
            <div style="text-align:right;font-size:11px;color:#374151">
                <div style="font-size:16px;font-weight:700;margin-bottom:4px">
                    SYSTEM AUDIT LOG REPORT
                </div>
                <div>Generated: {{ now()->timezone('Asia/Kuala_Lumpur')->format('d M Y, H:i:s') }}</div>
                <div>Generated by: {{ Auth::user()->Username }}</div>
                <div>Total Records: {{ $logs->count() }}</div>
            </div>
        </div>
    </div>

    {{-- Screen header --}}
    <div class="screen-header no-print"
         style="display:flex;justify-content:space-between;align-items:center;
                padding:16px 20px;background:#064e3b;border-radius:13px 13px 0 0">
        <span style="font-size:14px;font-weight:700;color:#fff">
            <i class="fa fa-history me-2"></i>Audit Log Records
        </span>
        <span style="font-size:11px;color:rgba(255,255,255,0.6)">
            {{ $logs->count() }} record(s)
            @if(request()->hasAny(['username','action','date_from','date_to']))
                — Filtered
            @endif
        </span>
    </div>

    {{-- Table --}}
    <div style="overflow-x:auto;border:1px solid #e2e8f0;
                border-radius:{{ $logs->count() ? '0 0 13px 13px' : '0 0 13px 13px' }}">
        <table class="audit-table">
            <thead>
                <tr>
                    <th>Timestamp</th>
                    <th>Username</th>
                    <th>Module</th>
                    <th>Action</th>
                    <th>Description</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($logs as $log)
                @php
                    $module = match(true) {
                        str_contains($log->Action, 'LOGIN') || str_contains($log->Action, 'LOGOUT') => 'Auth',
                        str_contains($log->Action, 'VENDOR') || str_contains($log->Action, 'PROFILE') => 'Module 1',
                        str_contains($log->Action, 'DO') => 'Module 2',
                        str_contains($log->Action, 'INVOICE') => 'Module 3',
                        default => 'System'
                    };
                    $isError = in_array($log->Action, ['LOGIN_FAILED','LOGIN_BLOCKED']);
                @endphp
                <tr class="{{ $loop->even ? 'row-even' : '' }}">
                    <td class="td-timestamp">
                        {{ $log->Timestamp
                            ? \Carbon\Carbon::parse($log->Timestamp)->timezone('Asia/Kuala_Lumpur')->format('Y-m-d H:i:s')
                            : '—' }}
                    </td>
                    <td class="td-username">
                        {{ $log->user->UserEmail ?? ('UserID:' . $log->UserID) }}
                    </td>
                    <td class="td-module">
                        <span class="module-badge module-{{ strtolower(str_replace(' ','',$module)) }}">
                            {{ $module }}
                        </span>
                    </td>
                    <td class="td-action">
                        <strong>{{ $log->Action }}</strong>
                    </td>
                    <td class="td-desc">
                        {{ $log->LogDescription ?? '—' }}
                    </td>
                    <td class="td-status">
                        @if($isError)
                            <span class="status-badge status-fail">Failed</span>
                        @else
                            <span class="status-badge status-success">Success</span>
                        @endif
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6" style="text-align:center;padding:48px;color:#9ca3af">
                        <i class="fa fa-search" style="font-size:28px;display:block;
                                  margin-bottom:12px;opacity:.3"></i>
                        No audit log records found.
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    {{-- Print footer --}}
    <div class="print-footer" style="display:none;margin-top:20px;text-align:center;
                font-size:10px;color:#6b7280;border-top:1px solid #e2e8f0;padding-top:12px">
        KTMeDOIS System Audit Log — Keretapi Tanah Melayu Berhad — CONFIDENTIAL
    </div>

</div>

@push('styles')
<style>
    .audit-doc {
        background: #fff;
        border-radius: 14px;
        overflow: hidden;
    }

    .audit-table {
        width: 100%;
        border-collapse: collapse;
        font-size: 13px;
        font-family: 'Segoe UI', Arial, sans-serif;
    }

    .audit-table thead tr {
        background: #f8fafc;
        border-bottom: 2px solid #000;
    }

    .audit-table th {
        padding: 12px 14px;
        text-align: left;
        font-size: 13px;
        font-weight: 700;
        color: #111827;
        border: 1px solid #d1d5db;
    }

    .audit-table td {
        padding: 10px 14px;
        border: 1px solid #d1d5db;
        color: #374151;
        vertical-align: top;
    }

    .row-even td { background: #f9fafb; }

    .td-timestamp { font-family: monospace; font-size: 12px; white-space: nowrap; }
    .td-username  { font-size: 12px; color: #1e3a8a; font-weight: 600; }
    .td-module    { white-space: nowrap; }
    .td-action    { white-space: nowrap; font-size: 12px; }
    .td-desc      { font-size: 12px; color: #6b7280; max-width: 260px; }
    .td-status    { white-space: nowrap; text-align: center; }

    .module-badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 20px;
        font-size: 11px;
        font-weight: 700;
    }
    .module-auth     { background: #e5e7eb; color: #374151; }
    .module-module1  { background: #dbeafe; color: #1d4ed8; }
    .module-module2  { background: #d1fae5; color: #065f46; }
    .module-module3  { background: #fef3c7; color: #92400e; }
    .module-system   { background: #ede9fe; color: #7c3aed; }

    .status-badge {
        display: inline-block;
        padding: 3px 12px;
        border-radius: 20px;
        font-size: 11px;
        font-weight: 700;
    }
    .status-success { background: #dcfce7; color: #166534; }
    .status-fail    { background: #fee2e2; color: #991b1b; }

    @media print {
        .no-print { display: none !important; }
        .print-header, .print-footer { display: block !important; }
        .ktm-sidebar, .ktm-topbar { display: none !important; }
        .ktm-main { margin-left: 0 !important; }
        .ktm-content { padding: 10px !important; }
        .audit-doc { border-radius: 0; }
        .audit-table th, .audit-table td { font-size: 11px; padding: 7px 10px; }
        .screen-header { display: none !important; }
    }
</style>
@endpush

@endsection
